### PR TITLE
Fix native callback parameters.

### PR DESCRIPTION
**Pull request by ollydev**
TLapeType_NativeMethod BaseType is ltUnknown so unable to convert type. Added a VarType check to handle as a pointer.

Seems to fix the issue without breaking anything else i've noticed.

### CODE REVIEW

**Comment by Olly-** [comment]
@nielsAD This fix does work for method of objects. The current testing format makes it hard to test callbacks, how about adding this to LapeTestFFI?

The following tests form callbacks & this PR though a script.

```pascal
type
  TMagicFunction = function: Int32; {$I cconv.inc}
  TProcedureOfObject = procedure(Magic: TMagicFunction) of object; {$I cconv.inc}

function Magic: Int32; {$I cconv.inc}
begin
  Result := 1989;
end;

procedure Lape_TestCallback(Params: PParamArray);
begin
  TProcedureOfObject(Params^[0]^)(@Magic);
end;

procedure FFI_TestCallbacks;
begin
  try
    with TLapeCompiler.Create(TLapeTokenizerString.Create(
      'type TPoint = record X, Y: Int32; end;'                                   + LineEnding +
      ''                                                                         + LineEnding +
      'procedure TPoint.Test(Magic: TMagicFunction);'                            + LineEnding +
      'begin'                                                                    + LineEnding +
      '  Assert(Lapify(Magic)() = 1989, ' + #39 + 'Magic() <> 1989' + #39 + ');' + LineEnding +
      '  Assert(Self.X = 50, ' + #39 + 'Self.X <> 50' + #39 + ');'               + LineEnding +
      '  Assert(Self.Y = 100, ' + #39 + 'Self.Y <> 100' + #39 + ');'             + LineEnding +
      'end;'                                                                     + LineEnding +
      ''                                                                         + LineEnding +
      'var P: TPoint = [50, 100];'                                               + LineEnding +
      'begin'                                                                    + LineEnding +
      '  TestCallback(@P.Test);'                                                 + LineEnding +
      'end;')) do
    try
      Options := Options + [lcoAssertions];

      InitializeFFI(GetSelf() as TLapeCompiler);

      addGlobalType('function: Int32;', '_TMagicFunction');
      addGlobalType('native(_TMagicFunction, ' + 'ffi_' + ABIToStr(TEST_ABI) + ')', 'TMagicFunction');

      addGlobalType('procedure(Magic: TMagicFunction) of object', '_TProcedureOfObject');
      addGlobalType('native(_TProcedureOfObject, ' + 'ffi_' + ABIToStr(TEST_ABI) + ')', 'TProcedureOfObject');

      addGlobalFunc('procedure TestCallback(Proc: TProcedureOfObject)', @Lape_TestCallback);

      if Compile() then
        RunCode(Emitter.Code);
    finally
      Free();
    end;

    WriteLn('Passed FFI_TestCallback');
  except
    on e: Exception do
    begin
      WriteLn('Failed FFI_TestCallback: ', e.Message);
    end;
  end;
end;
```

**Comment by Olly-** [comment]
@nielsAD I added a test. Unable to add a test for method of object callback parameter until [this](https://github.com/nielsAD/lape/issues/107#issuecomment-404155438) is resolved.

**Comment by ollydev** [comment]
@nielsAD Finished the tests. (used natify rather than native)

[This](https://github.com/nielsAD/lape/issues/107#issuecomment-404155438) bug can be for another time, I don't see anyone else having a script method with a native method parameter.

**Comment by nielsAD** [comment]
Thanks!

**Pull request merged**
